version: "3"
services:

  postgres:
    build: ./server/packages/db
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432
    image: mirror.gcr.io/library/nginx:alpine
  go-api:
    build: ./server
    ports:
      - 4000:4000
    depends_on:
      - postgres
    links:
      - postgres
    image: mirror.gcr.io/library/nginx:alpine
  react-app:
    build: ./client
    ports:
      - 3000:3000
    image: mirror.gcr.io/library/nginx:alpine
